platform :ios, '17.0'

target 'Aether' do
  use_frameworks!

  # WebRTC-SDK - LiveKit's WebRTC build with arm64 simulator support
  pod 'WebRTC-SDK', '~> 137.7151'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
