name: Aether
options:
  bundleIdPrefix: com.aether
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"

packages:
  WebRTC:
    url: https://github.com/nicklama/WebRTC-SPM
    from: "130.0.0"

targets:
  Aether:
    type: application
    platform: iOS
    sources:
      - path: Aether
        excludes:
          - "Info.plist"
    info:
      path: Aether/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIStatusBarStyle: UIStatusBarStyleLightContent
        NSMicrophoneUsageDescription: "Aether needs microphone access for voice conversations"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aether.app
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: WebRTC
